<h1>Editor</h1>
<?php foreach ($this->posts as $post) : ?>
<div class="row">
  <div class="span12">
    <div class="thumbnail">
    <img src="" alt="Thumb <?php echo $post->getCategory() ?>">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p><?php echo $post->getContent() ?></p>
        <p>
            <a href="editor/edit/<?php echo $post->getId() ?>">
                <button type="button" class="btn btn-default btn-lg">
                    <span class="glyphicon glyphicon-edit"></span> Edit 
                </button>
            </a>
        </p>
      </div>
    </div>
  </div>
</div>
<?php endforeach ?>
