<?php
if (!isset($__VIEWFILE__)) {
    throw new \Exception('$__VIEWFILE__ variable must be set with __FILE__ constant from the view file, in order for the partial to work.');
}

$fileparts = explode('/', $__VIEWFILE__);
$action = substr(end($fileparts), 0, -6);
$controller = prev($fileparts); 
$textdomain = prev($fileparts);
$route = array(
    'action' => $action
);
if (isset($entityId) && null !== $entityId) {
    $route['id'] = $entityId;
}
$this->formActionPrepare($form) ?>

<?php
$title = ucfirst($action) . ' ' . ucfirst($controller);
$this->headTitle($title);
?>
<header class="row">
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
    <div class="col-sm-12 col-md-8 col-lg-8">
        <h3><?php echo $this->escapeHtml($this->translate($title)); ?></h3>
    </div>
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
</header>

<div class="row">
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
    <div class="col-sm-12 col-md-8 col-lg-8">
        <?= $this->renderForm($form) ?>
    </div>
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
</div>
