<?php
if (!isset($__VIEWFILE__)) {
    throw new \Exception('$__VIEWFILE__ variable must be set with __FILE__ constant from the view file, in order for the partial to work.');
}

$fileparts = explode('/', $__VIEWFILE__);
$action = substr(end($fileparts), 0, -6);
$singular = $controller = prev($fileparts); 
$textdomain = prev($fileparts);

$plural   = 'Categories';

$title = $plural;
$this->headTitle($title);
$form->setAttribute('action', $this->url(null ,array('action' => 'bulk'), true));
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('role', 'form');
$form->prepare();
?>
<!-- Add New Category Button Row -->
<div class="row">
    <div class="col-sm-4 col-md-4 col-4">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="col-sm-4 col-md-4 col-4">
    </div>
    <div class="col-sm-4 col-md-4 col-4">
        <p><a class="btn btn-success" href="<?php echo $this->url(
            null, 
            array(
                'action'=>'create',
            ),
            true
        )?>"><?php echo $this->translate('Add New ' . ucfirst($singular)) ?></a></p>
    </div>
</div><!-- ENDOF Add New Category Button Row-->

<!-- Form action dropdown and submit Row -->
<?php echo $this->form()->openTag($form) ?>
<div class="form-group listing">
    <div class="col-sm-4 col-md-4 col-lg-4">
        <?php echo $this->formElement($form->get('action-top')) ?>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <?php echo $this->formElement($form->get('submit')) ?>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4">
<!-- Page selector -->
    <?php echo $this->paginator($paginator) ?>
<!-- ENDOF Page selector -->
    </div>
</div><!-- ENDOF Form action dropdown and submit Row -->

<table class="table table-bordered table-hover">
    <tr>
        <th><?php echo $this->translate('Bulk')?></th>
        <th><?php echo $this->translate('Category')?></th>
        <th><?php echo $this->translate('Lang')?></th>
<?php if ($user->isAdmin()) : ?>
        <th><?php echo $this->translate('Translated Id')?></th>
<?php endif ?>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($categories as $category) : ?>
	    <tr>
            <td><input type="checkbox" name="categories[]" value="<?php echo $this->escapeHtml($category['id']) ?>"></td>
            <td style="padding-left:<?php echo ($category['lvl'] * 2) + 1?>em;"><?php echo $category['name'];?></td>
	        <td><?php echo $this->translate($category['locale']) ?></td>
<?php if ($user->isAdmin()) : ?>
            <td><?php echo ((isset($category['translated_category_id']))? $category['translated_category_id'] : $this->translate('N/A')) ?></td>
<?php endif ?>
	        <td>
                <a href="<?php echo $this->url(
                    null, 
                    array(
                        'action'=>'edit', 
                        'id' => $category['id']
                    ),
                    true
                ); ?>"><?php echo $this->translate('Edit') ?></a>
	        </td>
	        <td>
                <a href="<?php echo $this->url(
                    null, 
                    array(
                        'action'=>'delete', 
                        'id' => $category['id'],
                        'nonce' => $nonce,
                    ),
                    true
                ); ?>" onclick="return confirm('Are you sure?')"><?php echo $this->translate('Delete') ?></a>
	        </td>
	    </tr>
    <?php endforeach; ?>
    <?php if (empty($categories)) : ?>
	    <tr>
            <td><?php echo $this->translate('You have not added any category for the moment...')?></td>
	    </tr>
    <?php endif ?>
</table>
<div class="form-group listing">
    <div class="col-sm-4 col-md-4 col-lg-4">
        <?php echo $this->formElement($form->get('action-bottom')) ?>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <?php echo $this->formElement($form->get('submit')) ?>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <?php echo $this->paginator() ?>
    </div>
</div>
<?php echo $this->form()->closeTag();?>
