<?php $this->notify(((isset($messages))? $messages : array())) ?>
<div class="row">
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
    <div class="col-sm-10 col-md-8 col-lg-8">
        <header class="row">
            <div class="col-sm-8 col-md-8 col-8">
                <?php $patterns = array(':dogname')?>
                <?php $replacements = array($dog->getName())?>
                <h3><?= $this->patternTranslate($patterns, $replacements, "Woff!! I'm :dogname") ?></h3>
            </div>
            <div class="col-sm-4 col-md-4 col-4">
            </div>
        </header>
        <div class="row">
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-3">
                <img class="img-responsive img-rounded" src="<?= $dog->getMedia()->getSrc() ?>" alt="<?= $dog->getName() . ' ' .  $this->translate('Media')?>"/>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8 col-lg-9">
                <?php $shadowColor = $this->colors()->brightenByPercent($dog->getColor(), 20)->toString() ?>
                <?php $borderColor = $this->colors()->darkenByPercent($dog->getColor(), 10)->toString() ?>
                <?php $textColor = $this->colors()->readableTextover($dog->getColor(), $onAverageBrighten=true)->toString() ?>
                <div class="panel" style="border-color: #<?= $borderColor ?>;">
                    <div class="panel-heading" style="color: #<?= $textColor ?>;background-image: linear-gradient(to bottom, #<?= $dog->getColor() ?> 0px, #<?= $shadowColor ?> 100%); backgroud-repeat: repeat-x;"><?= $this->translate('Info')?></div>
                    <ul class="list-group">
                        <li class="list-group-item"><?= $this->translate('Weight') ?>: <strong><?= $this->patternTranslate(array(':n'), array($dog->getWeightkg()), ':n Kg') ?></strong></li>
                        <li class="list-group-item"><?= $this->translate('Gender') ?>: <strong><?= $this->translate((('f' === $dog->getGender())? 'Female': 'Male')) ?></strong></li>
                        <li class="list-group-item"><?= $this->translate('Breed') ?>: <strong><?= $dog->getBreed() ?></strong></li>
                        <li class="list-group-item"><?= $this->translate('Born in') ?>: <strong><?= $dog->getBirthdate()->format('Y-m-d') ?></strong></li>
                    </ul>
                    <?php $userProfileUrl       = $this->url('profile_publicly_available', array('uniquename' => $this->identity()->getUniquename(),), true); ?>
                    <?php $userProfileLinkTitle =  $this->patternTranslate(array(':user'), array($this->identity()->getUniquename()), 'View :user\'s Profile'); ?>
                    <?php $userProfileLink      = "<a href=\"$userProfileUrl\" title=\"{$userProfileLinkTitle}\">{$this->identity()->getUniquename()}</a>" ?>
                    <?php $dogname              = "<strong>{$dog->getName()}</strong>"?>
                    <?php $patterns = array(':owner', ':dog', ':user_sentence') ?>
                    <?php $replacements = array($userProfileLink, $dogname, $dog->getWhythisdog()) ?>
                    <div class="panel-body"><p><?= $this->patternTranslate($patterns, $replacements, ":owner says: \"I chose :dog because :user_sentence.\"") ?></p></div>
                </div> <!-- end panel -->
            </div><!-- end col -->
        </div><!-- end row -->

        <?php $masonryColumnWidth = 180 ?>
        <div class="brick-wall row gbili-add-media-button-container">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <ul class="please_masonize_<?= $masonryColumnWidth ?>">
                <?php foreach($medias as $media) : ?>
                    <li>
                        <a href="<?= $this->url('blog_media_view', array('slug' => $media->getSlug()), true) ?>"><img class="img-responsive" src="<?= $this->escapeHtml($media->getFile()->getSrc());?>"></a>
                        <div class="caption">
                             <h5><?= $this->escapeHtml($media->getSlug());?></h5>
                        </div><!-- end caption -->
                   </li><!-- end thumbnail -->
                <?php endforeach ?>
                </ul><!--masonize -->
                <?php if (empty($medias)) : ?>
                    <p><?= $this->translate('No medias have been uploaded') ?></p>
                <?php endif ?>
            </div><!-- end col -->
         </div><!-- end row -->
        <?php require_once __DIR__ . '/../../../../Blog/view/partial/init_masonry.js.phtml' ?> 
    </div><!-- end col -->
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
</div><!-- end row -->
<?= $this->uploader()?>
