<?= $this->doctype() ?>
<html lang="<?php echo $this->lang() ?>">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Dogtore Understand your Dog')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
                             ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

        <!-- Le styles -->
        <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                 ->prependStylesheet($this->basePath() . '/css/style.css')
                 ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                 ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                 //Only add when in media forms
                 ->prependStylesheet($this->basePath() . '/css/image-picker.css') ?>


        <!-- Scripts -->
        <?= $this->headScript()
                 ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                 ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                 ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                 ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('scs_scs_index_route', array(), true) ?>"><?= $this->translate('Scs App', 'scs') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?= $this->renderNavigation(array('navigation' => 'default'), 'partial/topnav.phtml') ?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <div class="row">
                    <?php $sm=12;$md=12;$lg=12;?>
                    <?php $groupedContainers = array('side_1', 'side_2', 'side_3') ?>
                    <?php if ($this->conditionalNavigation()->isMatchedRouteContained($groupedContainers)) :?>
                        <!-- Side nav -->
                        <div class="col-sm-12 col-md-3 col-lg-2">
                            <?= $this->renderNavigation($groupedContainers, 'partial/sidenav.phtml') ?>
                        </div>
                        <?php $sm=12;$md=9;$lg=9;?>
                    <?php endif ?>
                    <div class="col-sm-<?=$sm?> col-md-<?=$md?> col-lg-<?=$lg?>">
                        <?= $this->renderNavigation(array('navigation' => 'default'), 'partial/breadcrumbs.phtml') ?>
                        <div class="row">
                            <div class="col-sm-1 col-md-2 col-lg-2"></div>
                            <div class="col-sm-10 col-md-8 col-lg-8">
                                <div id="messages">
                                   <?= $this->notify()->renderAll() ?>
                                </div>
                            </div>
                            <div class="col-sm-1 col-md-2 col-lg-2"></div>
                        </div>
                    <?= $this->content; ?>
                </div> 
            </div><!-- end row -->
            <hr>
            <footer>
                <p>&copy; 2009 - <?= date('Y') ?> <?php echo $this->translate('by', 'dogtore')?> dogtore.com. <?= $this->translate('All rights reserved.', 'dogtore') ?></p>
            </footer>
            <div id="footer-scripts">
                <?= $this->scriptalicious()->renderAll() ?>
            </div>
        </div> <!-- /container -->
    </body>
</html>
