<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <img src="<?php echo $entity->getFile()->getSrc(); ?>">
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
    <a href="<?php echo $this->url('blog_media_route' , array(
                                       'lang' => $this->lang(),
                                       'action' => 'index',
                                  ));
            ?>"><?php $this->translate('Back to media library', 'blog')?></a>
    </div>
</div>
