<div id="posts-container">
    <?php foreach ($posts as $post) : ?>
<?php //Guard against post whose category is not a child of an lvl1 category 
      //TODO find a better solution, like not allowing to save uncategorized ?>
    <?php if (!isset($post['post_category_slug'])) {throw new \Exception('Application Error, the current posts must have a category_slug');}?>
    <?php $post['post_category_name'] = $this->translate(ucfirst($post['post_category_slug'])) ?>
    <?php if (isset($post['parent_post_category_slug'])) : ?>
        <?php $post['parent_post_category_name'] = $this->translate(ucfirst($post['parent_post_category_slug'])) ?>
    <?php endif ?>
    <?php if (isset($post['child_post_category_slug'])) : ?>
        <?php $post['child_post_category_name'] = $this->translate(ucfirst($post['child_post_category_slug'])) ?>
    <?php endif ?>
    <div class="row post-row">
      <div class="col-xs-1 col-md-2 col-lg-2"></div>
      <div class="col-xs-10 col-md-8 col-lg-8">
        <div class="row post-wrap">
         <!-- <div class="col-xs-1 col-md-1 col-lg-1"><div class="arrow-left <?= ((null !== $post['parent_post_slug'])? $this->cssClass($post['parent_post_category_slug']) : 'disabled') ?>"></div></div> -->
          <div class="col-xs-12 col-md-12 col-lg-12">
            <div class="row thumbnail post <?= $this->translate($post['post_category_slug'], null, 'en')?>">
              <div class="col-xs-3 col-md-2 col-lg-2">
                <img class="img-responsive" src="<?= $post['media_src'] ?>" alt="Thumb <?= $post['post_category_slug'] ?>">
              </div><!-- col -->
              <div class="col-xs-9 col-md-10 col-lg-10">
                <?= $this->postLabels($post)?>
                <div class="caption">
                  <?php $terms = ((isset($terms))? $terms : array()) ?>
                  <h3><?= $this->highlight($this->escapeHtml($post['post_title']), $terms) ?></h3>
                  <p><?= $this->highlight($this->nlToBr($this->escapeHtml($post['post_content'])), $terms) ?></p>
                  <div class="btn-group">
                    <?= $this->postButtons($post) ?>
                  </div><!-- btn-group -->
                </div><!-- caption -->
              </div><!-- col -->
            </div><!-- row thumbnail post -->
        <?php if ($this->identity() && $this->identity()->getUniquename() === $post['user_uniquename']) : ?>
            <div class="row post-owned">
              <div class="col-xs-1 col-md-1 col-lg-1"></div>
              <div class="col-xs-10 col-md-10 col-lg-10">
                <div class="row post-controls">
                  <div class="col-xs-3 col-md-2 col-lg-2">
                    <?= $this->postButtons($post, 'edit')?>
                  </div>
                  <div class="col-xs-9 col-md-10 col-lg-10"></div>
                </div>
              </div>
              <div class="col-xs-1 col-md-1 col-lg-1"></div>
            </div>
        <?php endif ?>
          </div><!-- wrapping col-10 -->
          <!-- <div class="col-xs-1 col-md-1 col-lg-1"><div class="arrow-right <?= ((null !== $post['child_post_slug'])? $this->cssClass($post['child_post_category_slug']) : 'disabled') ?>"></div></div> -->
        </div> <!-- row post-wrap -->
      </div><!-- col -->
      <div class="col-xs-1 col-md-2 col-lg-2"></div>
    </div><!-- row post-row -->
    <?php endforeach ?>
</div>
